Handle build failures

diff --git a/common/clean-chroot-manager64.in b/common/clean-chroot-manager64.in
--- a/common/clean-chroot-manager64.in
+++ b/common/clean-chroot-manager64.in
@@ -101,7 +101,7 @@ check() {
   fi
 
   if [[ ! -f "$DEFAULT_MAKEPKG" ]]; then
-    local mesg="Invalid DEFAULT_MAKEPKG file defined in $SKEL"
+    local mesg="Invalid DEFAULT_MAKEPKG file defined in $CFGFILE"
     echo -e "${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}" && exit 1
   fi
 
@@ -162,6 +162,11 @@ addit() {
 build() {
   local mesg="Attempting to build package..."
   echo -e "${YELLOW}---->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}"
+  
+  if [[ ! -f PKGBUILD ]];then
+    local mesg="This must be run in a directory containing a PKGBUILD."
+    echo -e "${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}" && exit 1
+  fi
 
   makechrootpkg_opt="$1"
   makepkg_opt="$2"
@@ -173,23 +178,20 @@ build() {
     makechrootpkg_opt="$makechrootpkg_opt -d $TMP_BUILDDIR:/build"
   fi
 
-  nice -19 makechrootpkg $namcap_opt -u $makechrootpkg_opt -r "$CHROOTPATH64" -- $makepkg_opt
-  ret=$?
+  nice -19 makechrootpkg $namcap_opt -u $makechrootpkg_opt -r "$CHROOTPATH64" -- $makepkg_opt || true
 
   . PKGBUILD
   # makepkg can fail to build without throwing an error code so stop if
   # no .pkg.tar* is present in the dir
-  [[ -n $(find . -maxdepth 1 -type f -name "*$pkgver-$pkgrel*.pkg.tar*") ]] || exit 1
+  if [[ ! -n $(find . -maxdepth 1 -type f -name "*$pkgver-$pkgrel*.pkg.tar*") ]];then
+    local mesg="Build failed. See '$TMP_BUILDDIR'."
+    echo -e "${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}" && exit 1
+  fi
   
   if [[ -n "$TMP_BUILDDIR" ]];then
-    if [[ $ret -eq 0 ]];then
-        local mesg="Cleaning $TMP_BUILDDIR..."
-        echo -e "${YELLOW}---->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}"
-        find "$TMP_BUILDDIR" -mindepth 1 -maxdepth 1 | xargs -L1 -I{} bash -c "echo rm '{}' && rm -rf '{}'"
-    else
-        local mesg="Build failed. See '$TMP_BUILDDIR'."
-        echo -e "${YELLOW}---->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}"
-    fi
+    local mesg="Cleaning $TMP_BUILDDIR..."
+    echo -e "${YELLOW}---->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}"
+    find "$TMP_BUILDDIR" -mindepth 1 -maxdepth 1 | xargs -L1 -I{} bash -c "echo rm '{}' && rm -rf '{}'"
   fi
 
   return 0
