Add option to not clean chroot before building
This is helpful for example when the same group of packages are being
built, so that dependencies do not need to be reinstalled for each package.

diff --git a/common/clean-chroot-manager32.in b/common/clean-chroot-manager32.in
--- a/common/clean-chroot-manager32.in
+++ b/common/clean-chroot-manager32.in
@@ -133,55 +133,60 @@ build() {
 	local mesg="Attempting to build package..."
 	echo -e "${YELLOW}---->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}"
 
-    chrootcopy=$USER
-    [[ -n $SUDO_USER ]] && chrootcopy=$SUDO_USER
-    [[ -z "$chrootcopy" || $chrootcopy = root ]] && chrootcopy=copy
+	workingcopy=$USER
+	[[ -n $SUDO_USER ]] && workingcopy=$SUDO_USER
+	[[ -z "$workingcopy" || $workingcopy = root ]] && workingcopy=copy
 
-	if [[ -z "$RUNNAMCAP" ]]; then
-		makechrootpkg -c -u -r $CHROOTPATH32
-	else
-		makechrootpkg -c -u -n -r $CHROOTPATH32
+	if [[ "$1" != "noclean" ]];then
+		option="-c"
 	fi
 
-	# stop here if build fails
-	[[ $? -gt 0 ]] && exit 1
+	if [[ ! -z "$RUNNAMCAP" ]]; then
+		option="$option -n"
+	fi
+
+	makechrootpkg $option -u -r $CHROOTPATH32 || exit 1     # stop here if build fails
 
 	# if this is the first time package has been successfully built
 	# then append the local repo to the chroot's pacman.conf
 	if [[ -z $(grep clean-chroot $CHROOTPATH32/root/etc/pacman.conf) ]]; then
-		# add a local repo to chroot
-		cat << EOF >> $CHROOTPATH32/root/etc/pacman.conf
+		# add a local repo to chroot, both in root and working copy
+		for cuser in root $workingcopy;do
+			cat << EOF >> $CHROOTPATH32/$cuser/etc/pacman.conf
 
 # Added by $PKG
 [chroot_local]
 SigLevel = Never
 Server = file:///repo
 EOF
+		done
 	fi
 
-	# setup a local repo and add adjust files in chroot
-	[[ ! -d $CHROOTPATH32/root/repo ]] && mkdir $CHROOTPATH32/root/repo
+	# source PKGBUILD to get package details
+	. $CHROOTPATH32/$workingcopy/startdir/PKGBUILD
+	# save any changes in pkgver and pkgrel to PKGBUILD
+	sed -i "s/^pkgver=.*/pkgver=$pkgver/" PKGBUILD
+	sed -i "s/^pkgrel=.*/pkgrel=$pkgrel/" PKGBUILD
+
+	# setup a local repo and add adjust files in chroot, both in root and working copy
+	[[ ! -d $CHROOTPATH32/root/repo ]] && mkdir $CHROOTPATH32/{root,$workingcopy}/repo
 	local mesg="Adding package to chroot repo..."
 	echo -e "${YELLOW}---->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}"
-    # source PKGBUILD to get package details
-    . $CHROOTPATH32/$chrootcopy/startdir/PKGBUILD
-    # save any changes in pkgver and pkgrel to PKGBUILD
-    sed -i "s/^pkgver=.*/pkgver=$pkgver/" PKGBUILD
-    sed -i "s/^pkgrel=.*/pkgrel=$pkgrel/" PKGBUILD
-    # remove earlier versions of the package from repo
-    rm -f $REPO/$pkgname*.pkg.tar.xz
-    pkgpath=$(pwd) && [[ -n "$PKGDEST" ]] && pkgpath=$PKGDEST
-    pushd $pkgpath > /dev/null
-    for i in $pkgname-$pkgver-$pkgrel*.pkg.tar.xz; do
-		cp "$i" $REPO
-		repo-add $REPO/chroot_local.db.tar.gz $REPO/"$i" || exit 1
+	WORKINGCOPYPATH=$CHROOTPATH32/$workingcopy/repo
+	# remove earlier versions of the package from repo
+	rm -f {$REPO,$WORKINGCOPYPATH}/$pkgname*.pkg.tar.xz
+	pkgpath=$(pwd) && [[ -n "$PKGDEST" ]] && pkgpath=$PKGDEST
+	pushd $pkgpath > /dev/null
+	for i in $pkgname*-$pkgver-$pkgrel*.pkg.tar.xz; do
+		cp "$i" $REPO && repo-add $REPO/chroot_local.db.tar.gz $REPO/"$i" || exit 1
+		cp "$i" $WORKINGCOPYPATH && repo-add $WORKINGCOPYPATH/chroot_local.db.tar.gz $WORKINGCOPYPATH/"$i" > /dev/null || exit 1
 
 		# ensure that the chroot package matches the live pacman cache package
 		# which avoids checksum errors if the user builds the same $pkgname-$pkgver
 		# more than once
 		[[ -f "/var/cache/pacman/pkg/$i" ]] && rm -f "/var/cache/pacman/pkg/$i"
 	done
-    popd > /dev/null
+	popd > /dev/null
 
 	# The rm statement above can return 1 if the file to remove is not found,
 	# causing the function to return a non-zero error code even if everything
@@ -293,7 +298,7 @@ case "$1" in
 			mesg=
 			create
 		fi
-		build
+		build $2
 		;;
 	u)
 		check2 && update
@@ -308,6 +313,7 @@ case "$1" in
 		echo
 		echo -e ${BOLD}" --- BUILDING ---"${ALL_OFF}
 		echo -e ${BOLD}" s) Run makepkg in clean chroot"${ALL_OFF}
+		echo -e ${BOLD}" s noclean) Run makepkg in chroot, without cleaning it first"${ALL_OFF}
 		echo
 		echo -e ${BOLD}" --- MISCELLANEOUS ---"${ALL_OFF}
 		echo -e ${BOLD}" l) List local repo in chroot (packages you build)"${ALL_OFF}
