ccm: support -I calls at build time
Allow optional pre-built packages to be passed as extra positional
arguments to ccm s and S. For example:

% ccm s /scratch/rust-1_1.94.1-1-x86_64.pkg.tar.zst
equals:
% makechrootpkg -r /scratch/.chroot -I /scratch/rust-1_1.94.1-1-x86_64.pkg.tar.zst -- -A

diff --git a/common/clean-chroot-manager.in b/common/clean-chroot-manager.in
--- a/common/clean-chroot-manager.in
+++ b/common/clean-chroot-manager.in
@@ -506,6 +506,18 @@ build() {
   [[ -d "$CCACHE_DIR" ]] && args+=(-d "$CCACHE_DIR:/build/.ccache")
   [[ -d "$DISTCC_DIR" ]] && args+=(-d "$DISTCC_DIR:/build/.distcc")
 
+  for pkg in "${INJECT_PKGS[@]}"; do
+    if [[ ! -f "$pkg" ]]; then
+      local mesg="Inject package not found: $pkg"
+      echo -e "${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}"; exit 1
+    fi
+    if [[ "$pkg" != *.pkg.tar.* ]]; then
+      local mesg="File does not appear to be a package archive: $pkg"
+      echo -e "${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}"; exit 1
+    fi
+    args+=(-I "$pkg")
+  done
+
   if [[ -f "$CUSTOM_MAKEPKG_CONF" ]]; then
     # makechrootpkg reads MAKEFLAGS and PACKAGER from the defined makepkg.conf
     # so honor those values here by not prefixing the call to makechrootpkg
@@ -1159,6 +1171,7 @@ case "$1" in
     echo -e "${YELLOW}---->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}"
 
     # flag to add '-c' to the args array
+    INJECT_PKGS=("${@:2}")
     CLEANIT=1
     build || exit 1
     if [[ -n $GPGKEY ]]; then
@@ -1189,6 +1202,7 @@ case "$1" in
     echo -e "${YELLOW}---->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}"
 
     # flag to NOT add a '-c' to the args array
+    INJECT_PKGS=("${@:2}")
     CLEANIT=0
     build || exit 1
     GLOBIGNORE="*.log:*.sig"
@@ -1251,6 +1265,8 @@ case "$1" in
     echo -e "${BOLD}   R) Repackage (passes '-Rf' to default)${ALL_OFF}"
     echo -e "${BOLD}   S) Run makepkg but do not clean first${ALL_OFF}"
     echo -e "${BOLD}   s) Run makepkg (default)${ALL_OFF}"
+    echo -e "${BOLD}      Optionally append package(s) to install into the chroot before building${ALL_OFF}"
+    echo -e "${BOLD}      e.g. ccm s /path/foo.pkg.tar.zst /path/bar.pkg.tar.zst${ALL_OFF}"
     echo
     echo -e "${BOLD} --- LOCAL REPO ---${ALL_OFF}"
     echo -e "${BOLD}   a) Add packages in current dir to the local repo${ALL_OFF}"
