Update helper functions and give proper source from devtools

diff --git a/common/clean-chroot-manager64.in b/common/clean-chroot-manager64.in
--- a/common/clean-chroot-manager64.in
+++ b/common/clean-chroot-manager64.in
@@ -424,19 +424,39 @@ header() {
 }
 
 ##
+#  Copied from https://git.archlinux.org/devtools.git/tree/lib/archroot.sh
+##
+
+##
+#  Returns if the $path is a the root of a btrfs subvolume (including
+#           the top-level subvolume).
+#
+#  usage  : is_subvolume( $path )
+#  return : true if it is, false if not
+##
+is_subvolume() {
+	[[ -e "$1" && "$(stat -f -c %T "$1")" == btrfs && "$(stat -c %i "$1")" == 256 ]]
+}
+
+##
 #  Find all btrfs subvolumes under and including $path and delete them.
-#  https://git.archlinux.org/devtools.git/commit/?h=heftig&id=eec7fcf965763d5395c336f92cd56b193d054947
+#
+#  usage  : subvolume_delete_recursive( $path )
+#  return : 0 if it was successful, 1 if not.
 ##
 subvolume_delete_recursive() {
-  local subvol
-  while IFS= read -d $'\0' -r subvol; do
-    if ! btrfs subvolume delete "$subvol" &>/dev/null; then
-      local mesg="Unable to delete subvolume ${subvol}"
-      echo -e "${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}"
-      return 1
-    fi
-  done < <(find "$1" -xdev -depth -inum 256 -print0)
-  return 0
+	local subvol
+	is_subvolume "$1" || return 0
+	while IFS= read -d $'\0' -r subvol; do
+		if ! subvolume_delete_recursive "$subvol"; then
+			return 1
+		fi
+	done < <(find "$1" -mindepth 1 -xdev -depth -inum 256 -print0)
+	if ! btrfs subvolume delete "$1" &>/dev/null; then
+		error "Unable to delete subvolume %s" "$subvol"
+		return 1
+	fi
+	return 0
 }
 
 nuke() {
