Add support for BTRFS root FS.
When root FS is BTRFS devtools creates subvolumes for managing the
chroots. This commit handled deleting them when nuking the chroot by
recursively deleting the subvolumes.

diff --git a/common/clean-chroot-manager64.in b/common/clean-chroot-manager64.in
--- a/common/clean-chroot-manager64.in
+++ b/common/clean-chroot-manager64.in
@@ -91,11 +91,6 @@ check() {
       echo -e "${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}" && exit 1
     fi
 
-    if [[ $(stat -f -c %T "$CHROOTPATH64") == btrfs ]]; then
-      local mesg="BTRFS targets for building are not supported."
-      echo -e "${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}" && exit 1
-    fi
-
     REPO="$CHROOTPATH64/root/repo"
 
     if [[ "$THREADS" =~ ^[0-9]+$ ]]; then
@@ -428,10 +423,36 @@ header() {
   echo
 }
 
+##
+#  Find all btrfs subvolumes under and including $path and delete them.
+#  https://git.archlinux.org/devtools.git/commit/?h=heftig&id=eec7fcf965763d5395c336f92cd56b193d054947
+##
+subvolume_delete_recursive() {
+  local subvol
+  while IFS= read -d $'\0' -r subvol; do
+    if ! btrfs subvolume delete "$subvol" &>/dev/null; then
+      local mesg="Unable to delete subvolume ${subvol}"
+      echo -e "${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}"
+      return 1
+    fi
+  done < <(find "$1" -xdev -depth -inum 256 -print0)
+  return 0
+}
+
 nuke() {
   local mesg="Nuking the chroot..."
   echo -e "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}"
-  rm -rf "${CHROOTPATH64:?}"/*
+  if [[ $(stat -f -c %T "$CHROOTPATH64") == btrfs ]]; then
+    for i in "$CHROOTPATH64"/*; do
+      if [ -d "$i" ]; then
+        subvolume_delete_recursive "$i" || return -1
+      else
+        rm -f "$i"
+      fi
+    done
+  else
+    rm -rf "${CHROOTPATH64:?}"/*
+  fi
 }
 
 distcc_check() {
